In [1]:
import requests
import pandas as pd

israel_weather = None
cities = ['Jerusalem','Tel Aviv','Haifa','Holon','Bat Yam']

#We want to get get the current weather data for the above cities in Israel using the api from the site:
# https://weatherstack.com/

#Step 1: Create an account at https://weatherstack.com/signup/free
#Step 2: Find the base url and copy your access key from the page after you sign up
#Step 3: Create a loop on the array of cities above and using the get method in the python requests library 
#        fetch the current weather for each city
#Step 4: Use the json_normalize function of pandas to flatten and load the data that you got for each city
#Step 5: Using an if\else statement initialize the israel_weather variable to the first city dataframe if it is not initializes
#        If it is already initialized, then use the append method to add the data for the next city to your existing dataframe
#Step 6: Save your data to a csv file using the to_csv method of pandas
#Step 7: Check you csv file. Is the data for all the cities there? Are all the cities in Israel? 
#        If not, how can you fix this issue?

In [2]:
key_access = '8f64288e095ab1a0e95f03d417ab3422'
 # Fill it

for city in cities:
    response = requests.get('http://api.weatherstack.com/current?access_key='+key_access+'&query='+city)
    #print(response)
    j = response.json()
    #print(j)
    row = pd.json_normalize(j)
    #print(row)
    if israel_weather is None:
        israel_weather = row
    else:
        israel_weather = israel_weather.append(row)

israel_weather.to_csv("israel_weather.csv")

  request.type      request.query request.language request.unit location.name  \
0         City  Jerusalem, Israel               en            m     Jerusalem

  location.country location.region location.lat location.lon  \
0           Israel    Yerushalayim       31.780       35.230

  location.timezone_id  ... current.wind_degree  current.wind_dir  \
0       Asia/Jerusalem  ...                 280                 W

  current.pressure current.precip  current.humidity  current.cloudcover  \
0             1019              0                63                  40

  current.feelslike current.uv_index  current.visibility  current.is_day
0                 7                4                  10             yes

[1 rows x 29 columns]
  request.type          request.query request.language request.unit  \
0         City  Tel Aviv-Yafo, Israel               en            m

   location.name location.country location.region location.lat location.lon  \
0  Tel Aviv-Yafo           Israel        Tel Aviv       32.068       34.765

  location.timezone_id  ... current.wind_degree  current.wind_dir  \
0       Asia/Jerusalem  ...                 290               WNW

  current.pressure current.precip  current.humidity  current.cloudcover  \
0             1018              0                45                  50

  current.feelslike current.uv_index  current.visibility  current.is_day
0                17                5                  10             yes

[1 rows x 29 columns]
  request.type  request.query request.language request.unit location.name  \
0         City  Haifa, Israel               en            m         Haifa

  location.country location.region location.lat location.lon  \
0           Israel            Hefa       32.816       34.989

  location.timezone_id  ... current.wind_degree  current.wind_dir  \
0       Asia/Jerusalem  ...                 310                NW

  current.pressure current.precip  current.humidity  current.cloudcover  \
0             1018              0                51                  50

  current.feelslike current.uv_index  current.visibility  current.is_day
0                16                4                  10             yes

[1 rows x 29 columns]
  request.type  request.query request.language request.unit location.name  \
0         City  Holon, Israel               en            m         Holon

  location.country location.region location.lat location.lon  \
0           Israel        Tel Aviv       32.011       34.772

  location.timezone_id  ... current.wind_degree  current.wind_dir  \
0       Asia/Jerusalem  ...                 290               WNW

  current.pressure current.precip  current.humidity  current.cloudcover  \
0             1018              0                45                  50

  current.feelslike current.uv_index  current.visibility  current.is_day
0                17                4                  10             yes

[1 rows x 29 columns]
  request.type    request.query request.language request.unit location.name  \
0         City  Bat Yam, Israel               en            m       Bat Yam

  location.country location.region location.lat location.lon  \
0           Israel        Tel Aviv       32.023       34.750

  location.timezone_id  ... current.wind_degree  current.wind_dir  \
0       Asia/Jerusalem  ...                 290               WNW

  current.pressure current.precip  current.humidity  current.cloudcover  \
0             1018              0                45                  50

  current.feelslike current.uv_index  current.visibility  current.is_day
0                17                4                  10             yes

[1 rows x 29 columns]

In [3]:
israel_weather
#print(type(israel_weather))

,request.type,request.query,request.language,request.unit,location.name,location.country,location.region,location.lat,location.lon,location.timezone_id,...,current.wind_degree,current.wind_dir,current.pressure,current.precip,current.humidity,current.cloudcover,current.feelslike,current.uv_index,current.visibility,current.is_day
0,City,"Jerusalem, Israel",en,m,Jerusalem,Israel,Yerushalayim,31.780,35.230,Asia/Jerusalem,...,280,W,1019,0,63,40,7,4,10,yes
0,City,"Tel Aviv-Yafo, Israel",en,m,Tel Aviv-Yafo,Israel,Tel Aviv,32.068,34.765,Asia/Jerusalem,...,290,WNW,1018,0,45,50,17,5,10,yes
0,City,"Haifa, Israel",en,m,Haifa,Israel,Hefa,32.816,34.989,Asia/Jerusalem,...,310,NW,1018,0,51,50,16,4,10,yes
0,City,"Holon, Israel",en,m,Holon,Israel,Tel Aviv,32.011,34.772,Asia/Jerusalem,...,290,WNW,1018,0,45,50,17,4,10,yes
0,City,"Bat Yam, Israel",en,m,Bat Yam,Israel,Tel Aviv,32.023,34.750,Asia/Jerusalem,...,290,WNW,1018,0,45,50,17,4,10,yes

In [4]:
israel_weather
print(type(israel_weather))

<class 'pandas.core.frame.DataFrame'>